[[main]]
  name = "About"
  pageRef = "about"
  weight = 10

[[main]]
  name = "Services"
  pageRef = "services"
  weight = 20

[[main]]
  name = "Blog"
  pageRef = "posts"
  weight = 30

[[main]]
  name = "Portfolio"
  pageRef = "portfolio"
  weight = 40

[[main]]
  name = "Contact"
  pageRef = "contact"
  weight = 50
