baseURL = "https://blog.netcryptix.com/"
languageCode = "en"
title = "NetCryptix"
theme = "blowfish"

[author]
  name = "James MacDonald"
  headline = "Network & Security Architect"

[[menu.main]]
  name = "About"
  pageRef = "about"
  weight = 10

[[menu.main]]
  name = "Services"
  pageRef = "services"
  weight = 20

[[menu.main]]
  name = "Blog"
  pageRef = "posts"
  weight = 30

[[menu.main]]
  name = "Portfolio"
  pageRef = "portfolio"
  weight = 40

[[menu.main]]
  name = "Contact"
  pageRef = "contact"
  weight = 50

[markup.highlight]
  style = "monokai"

[markup.goldmark.renderer]
  unsafe = true

[taxonomies]
  category = "categories"
  tag = "tags"
  vendor = "vendors"
